services:
  puzzle_lab_web:
    image: puzzle_lab_web
    restart: unless-stopped
    depends_on:
      - puzzle_lab_api
    build:
      context: .
      dockerfile: ./src/PuzzleLab.Web/Dockerfile
    ports:
      - "8000:8000"

  puzzle_lab_api:
    image: puzzle_lab_api
    restart: unless-stopped
    depends_on:
      - database
    build:
      context: .
      dockerfile: ./src/PuzzleLab.API/Dockerfile
    ports:
      - "3000:3000"

  database:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: puzzle_lab
    ports:
      - "5432:5432"
    volumes:
      - puzzle_lab_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  puzzle_lab_data:
  rabbitmq_data: