services:
  puzzle_lab:
    image: puzzle_lab
    restart: unless-stopped
    depends_on:
      - database
    build:
      context: .
      dockerfile: ./src/PuzzleLab.Web/Dockerfile
    ports:
      - "8000:8000"

  database:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: puzzle_lab
    ports:
      - "5432:5432"
    volumes:
      - puzzle_lab_data:/var/lib/postgresql/data

volumes:
  puzzle_lab_data: